CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    CONSTRAINT PK_USER PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS textile
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    textile_name  VARCHAR(512)                            NOT NULL,
    color         VARCHAR(512)                            NOT NULL,
    status        VARCHAR(512)                            NOT NULL,
    length        INTEGER                                 NOT NULL,
    width         INTEGER                                 NOT NULL,
    delivery_time DATETIME,
    CONSTRAINT PK_TEXTILE PRIMARY KEY (id),

);